coverage:
  ignore:
    - "Sources/Core/Internal/MethodMaker.swift"
    - "Sources/Core/API/AutoResolve/DIContainer.Reg.swift"
    - "Sources/Core/API/AutoResolve/DIComponentBuilder.Injection.swift"
    - Documentation
    - Samples
    - SetupDependencies
    - Tests
  status:
    patch: false
    changes: false
comment: false
